//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaDynamicImportToolWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaDynamicImportTool), typeof(System.Object));
		L.RegFunction("Import", Import);
		L.RegFunction("New", _CreateLuaDynamicImportTool);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaDynamicImportTool(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaDynamicImportTool obj = new LuaDynamicImportTool();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaDynamicImportTool.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Import(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			LuaDynamicImportTool.Import(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

