//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MemoryOutputStreamSingletonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MemoryOutputStreamSingleton), typeof(MemoryOutputStream));
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MemoryOutputStreamSingleton o = MemoryOutputStreamSingleton.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

