//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SingletonObject_ResourcesManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SingletonObject<ResourcesManager>), typeof(System.Object), "SingletonObject_ResourcesManager");
		L.RegFunction("New", _CreateSingletonObject_ResourcesManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingletonObject_ResourcesManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SingletonObject<ResourcesManager> obj = new SingletonObject<ResourcesManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SingletonObject<ResourcesManager>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, SingletonObject<ResourcesManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

