//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WeChatPayWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WeChatPay), typeof(System.Object));
		L.RegFunction("SendWeChatPay", SendWeChatPay);
		L.RegFunction("New", _CreateWeChatPay);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWeChatPay(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				WeChatPay obj = new WeChatPay();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: WeChatPay.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendWeChatPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 7);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			string arg3 = ToLua.CheckString(L, 4);
			string arg4 = ToLua.CheckString(L, 5);
			string arg5 = ToLua.CheckString(L, 6);
			string arg6 = ToLua.CheckString(L, 7);
			WeChatPay.SendWeChatPay(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

